### ISSUE TITLE
Packet VPN api tends to return an error, breaking the ipset script

### ISSUE THREAD

**Issue by nervetattoo** [ContainerSolutions/dcos-ansible-packet#37]
I've noticed that the `user/vpn` endpoint tend to return this error message
```json
{"errors":["Oh snap, something went wrong! We've logged the error and will take a look - please reach out to us if you continue having trouble."]}
```

(You can test this out in the [interactive API docs of Packet](https://www.packet.net/developers/api/vpn/))

This in time makes the bash-fu end up with the following input to the vpn variable in ansible:
```
127.0.0.1
127.0.0.1
```

Apart from these IPs obviously not being the VPN ips, will break the script becase the second line will become its own line as the j2 template is compiled, and `127.0.0.1` is obviously not a recognisable command for bash :)

In our playbook we've just commented out this step of the whitelist for now

**Comment by frankscholten** [comment]
Ok I will remove it for now.
